### ISSUE TITLE
License issue: MuPDF is GNU AGPL licensed

### ISSUE THREAD

**Issue by robinwatts** [xiangxw/mupdf-qt#17]
MuPDF is GNU AGPL licensed. Your code therefore must be too.

You are not complying with the license. Please do so, or take this repo down.

Thanks.

**Comment by sunderme** [comment]
the wikipedia summary states that linking from GPLv3 to AGPLv3 components is well covered by both licenses. 
https://en.wikipedia.org/wiki/Affero_General_Public_License

"By contrast, GPLv3 and AGPLv3 each include clauses (in section 13 of each license) that together achieve a form of mutual compatibility for the two licenses. These clauses explicitly allow the "conveying" of a work formed by linking code licensed under the one license against code licensed under the other license,[3] despite the licenses otherwise not allowing relicensing under the terms of each other.[4] In this way, the copyleft of each license is relaxed to allow distributing such combinations.[4]"

So, what is your point ?

**Comment by robinwatts** [comment]
My apologies. Somehow, I missed the inclusion of the license in the top level. You are absolutely fine.

Sorry to have disturbed you!
